# Generated by Django 3.1.2 on 2020-10-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='terms_condtins',
            new_name='terms_condins',
        ),
    ]
