# Generated by Django 3.1.2 on 2020-10-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201011_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='profilePic/'),
        ),
    ]
