# Generated by Django 3.1.2 on 2020-10-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201012_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(default=0),
        ),
    ]
