# Generated by Django 3.1.2 on 2020-10-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201012_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_id',
        ),
    ]
