# Generated by Django 3.1.2 on 2020-10-23 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_remove_member_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Plasma', 'Plasma'), ('Platelet', 'Platelet')], max_length=100)),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_address', models.CharField(max_length=200)),
                ('hospital_contact_no', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('request_for', models.ManyToManyField(to='accounts.Member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
