# Generated by Django 3.1.2 on 2020-10-27 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_auto_20201026_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_for',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='request_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
