# Generated by Django 3.1.2 on 2020-10-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201028_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='req_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
