# Generated by Django 3.1.2 on 2020-10-28 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20201028_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 10, 41, 16, 594670, tzinfo=utc)),
        ),
    ]
