# Generated by Django 3.1.2 on 2020-10-28 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20201028_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='req_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
