# Generated by Django 3.1.2 on 2020-10-30 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0028_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Plasma', 'Plasma'), ('Platelet', 'Platelet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_contact_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='purpose',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
