# Generated by Django 3.1.2 on 2020-10-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availibility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
