# Generated by Django 3.1.2 on 2020-10-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availibility', '0002_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
