# Generated by Django 3.1.2 on 2020-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availibility', '0003_camp_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=100)),
                ('dr_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
