# Generated by Django 3.1.2 on 2020-10-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availibility', '0004_carecentre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecentre',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
