# Generated by Django 3.1.2 on 2020-10-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availibility', '0005_auto_20201014_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carecentre',
            name='time',
        ),
    ]
