# Generated by Django 3.1.2 on 2020-10-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availibility', '0006_remove_carecentre_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodavailibility',
            name='blood_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='blood_ab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='blood_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='blood_o',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='plasma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='platelet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='organizer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carecentre',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carecentre',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carecentre',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carecentre',
            name='dr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
