# Generated by Django 3.1.2 on 2020-10-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availibility', '0007_auto_20201019_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodavailibility',
            name='blood_a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='blood_ab',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='blood_b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='blood_o',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='plasma',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodavailibility',
            name='platelet',
            field=models.IntegerField(),
        ),
    ]
