# Generated by Django 3.1.2 on 2020-10-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availibility', '0008_auto_20201029_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camp',
            name='contact_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='camp',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='camp',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='camp',
            name='organizer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='camp',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carecentre',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carecentre',
            name='clinic_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carecentre',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carecentre',
            name='dr_name',
            field=models.CharField(max_length=100),
        ),
    ]
