# Generated by Django 3.1.2 on 2020-10-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideimg',
            name='img',
            field=models.ImageField(upload_to='slideImages/'),
        ),
    ]
